"""university short_name eklendi

Revision ID: 618639252cac
Revises: f8e32fe4060f
Create Date: 2026-07-24 13:02:32.636915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618639252cac'
down_revision: Union[str, Sequence[str], None] = 'f8e32fe4060f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('short_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'short_name')
    # ### end Alembic commands ###
