"""add user role, review unique constraint

Revision ID: 771bdfab1cee
Revises: 874920dca342
Create Date: 2026-07-23 21:13:27.521300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '771bdfab1cee'
down_revision: Union[str, Sequence[str], None] = '874920dca342'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_course_professor_review', 'reviews', ['user_id', 'course_professor_id'])

    user_role_enum = sa.Enum('student', 'admin', name='user_role')
    user_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'users',
        sa.Column(
            'role',
            user_role_enum,
            nullable=False,
            server_default='student',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum('student', 'admin', name='user_role')
    user_role_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint('uq_user_course_professor_review', 'reviews', type_='unique')
    # ### end Alembic commands ###
