"""fakülte eklendi

Revision ID: 85d91433d9a2
Revises: 032da0709f25
Create Date: 2026-07-26 16:33:48.992893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d91433d9a2'
down_revision: Union[str, Sequence[str], None] = '032da0709f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'faculties',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('university_id', sa.Integer(), sa.ForeignKey('universities.id'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.UniqueConstraint('university_id', 'name', name='uq_university_faculty_name'),
    )

    # Test verisi temizleniyor — FK zincirinde en alttan (yaprak) en üste (kök) doğru siliniyor
    op.execute('DELETE FROM reports')
    op.execute('DELETE FROM reviews')
    op.execute('DELETE FROM course_professors')
    op.execute('DELETE FROM courses')
    op.execute('DELETE FROM departments')

    op.drop_constraint('uq_university_department_name', 'departments', type_='unique')
    op.drop_column('departments', 'university_id')
    op.add_column('departments', sa.Column('faculty_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_departments_faculty_id', 'departments', 'faculties', ['faculty_id'], ['id']
    )
    op.create_unique_constraint('uq_faculty_department_name', 'departments', ['faculty_id', 'name'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('university_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_university_id_fkey'), 'departments', 'universities', ['university_id'], ['id'])
    op.drop_constraint('uq_faculty_department_name', 'departments', type_='unique')
    op.create_unique_constraint(op.f('uq_university_department_name'), 'departments', ['university_id', 'name'], postgresql_nulls_not_distinct=False)
    op.drop_column('departments', 'faculty_id')
    op.drop_table('faculties')
    # ### end Alembic commands ###
