"""professors tablosuna title kolonu eklendi

Revision ID: 8d594d8452ff
Revises: e24c0e47968f
Create Date: 2026-07-27 14:38:22.930457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d594d8452ff'
down_revision: Union[str, Sequence[str], None] = 'e24c0e47968f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('professors', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professors', 'title')
    # ### end Alembic commands ###
