"""review edit gölge alanları eklendi

Revision ID: b53d1808a1d1
Revises: caacfdb5c99e
Create Date: 2026-07-24 15:53:33.170354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b53d1808a1d1'
down_revision: Union[str, Sequence[str], None] = 'caacfdb5c99e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('pending_teaching_score', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('pending_difficulty_score', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('pending_fairness_score', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('pending_comment', sa.Text(), nullable=True))
    op.add_column('reviews', sa.Column('has_pending_edit', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'has_pending_edit')
    op.drop_column('reviews', 'pending_comment')
    op.drop_column('reviews', 'pending_fairness_score')
    op.drop_column('reviews', 'pending_difficulty_score')
    op.drop_column('reviews', 'pending_teaching_score')
    # ### end Alembic commands ###
