"""reviews tablosuna (course_professor_id, status) index'i eklendi

Revision ID: c68bdebc16e0
Revises: f4df406c73a5
Create Date: 2026-08-04 16:59:06.131996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c68bdebc16e0'
down_revision: Union[str, Sequence[str], None] = 'f4df406c73a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reviews_cp_status', 'reviews', ['course_professor_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_cp_status', table_name='reviews')
    # ### end Alembic commands ###
