"""department university_id+name unique constraint

Revision ID: caacfdb5c99e
Revises: 618639252cac
Create Date: 2026-07-24 13:13:22.401554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caacfdb5c99e'
down_revision: Union[str, Sequence[str], None] = '618639252cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_university_department_name', 'departments', ['university_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_university_department_name', 'departments', type_='unique')
    # ### end Alembic commands ###
