"""add unique constraint reporter_id review_id on reports

Revision ID: f8e32fe4060f
Revises: 771bdfab1cee
Create Date: 2026-07-23 22:04:32.625185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e32fe4060f'
down_revision: Union[str, Sequence[str], None] = '771bdfab1cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_reporter_review_report', 'reports', ['reporter_id', 'review_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_reporter_review_report', 'reports', type_='unique')
    # ### end Alembic commands ###
